name: soul

on:
  push:
  pull_request:
  schedule:
    - cron: '*/55 * * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [
          1, 2, 3, 4, 5, 6, 7, 8, 9, 10,
          11, 12, 13, 14, 15, 16, 17, 18, 19, 20,
          21, 22, 23, 24, 25, 26, 27, 28, 29, 30
        ]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install requirements
        run: |
          pip install requests telebot --break-system-packages

      - name: Prepare and Run Soul Worker ðŸš€
        timeout-minutes: 240
        run: |
          echo "Starting worker ${{ matrix.job }}"
          chmod +x soul
          python3 github.py
          echo "Worker ${{ matrix.job }} finished"
